# Generated by Django 3.0.8 on 2020-08-01 07:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Centro de Custo')),
                ('name_department', models.CharField(max_length=60, verbose_name='Departamento')),
                ('responsible', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('identifier', models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MaxValueValidator(999999999), django.core.validators.MinValueValidator(1)], verbose_name='Registro')),
                ('name', models.CharField(max_length=130, verbose_name='Nome Funcionário')),
                ('admission', models.DateTimeField(verbose_name='Admissão')),
                ('resignation', models.DateTimeField(null=True, verbose_name='Demissão')),
                ('birth_date', models.DateTimeField(null=True, verbose_name='Data de Aniversário')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('email', models.EmailField(blank=True, error_messages={'required': 'Porfavor digite seu e-mail.', 'unique': 'Já existe esse e-mail cadastrado.'}, max_length=70, null=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, null=True, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=12, verbose_name='CPF')),
                ('role', models.CharField(max_length=60, verbose_name='Cargo')),
                ('cost_center', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(11111)], verbose_name='CDC')),
                ('gender', models.CharField(choices=[('F', 'Feminino'), ('G', 'Masculino')], max_length=12, verbose_name='Gênero')),
                ('photo', models.ImageField(default='0000.jpg', max_length=200, upload_to='FotosFuncionarios', verbose_name='Fotos Funcionários')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
