# Generated by Django 3.1 on 2020-08-19 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200801_0415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='costcenter',
            options={'verbose_name_plural': 'CostCenter'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.TextField(default=1, max_length=200, verbose_name='Bio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cost_center',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.costcenter', verbose_name='Centro de Custo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=stdimage.models.StdImageField(default='0000.jpg', upload_to='FotosFuncionarios'),
        ),
        migrations.AddField(
            model_name='employee',
            name='unity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='users.unity'),
            preserve_default=False,
        ),
    ]
