# Generated by Django 2.2 on 2020-08-20 03:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import performance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0006_auto_20200819_2328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('year', models.PositiveIntegerField(default=performance.models.current_year, verbose_name='Ano')),
                ('rated', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rated_evaluations', to='users.Employee', verbose_name='Avaliado')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modified', models.DateField(auto_now_add=True, verbose_name='Atualização')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('grade', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Nota')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_skills', to='performance.Evaluation', verbose_name='Avaliação')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_skills', to='performance.Skill', verbose_name='Habilidade')),
            ],
            options={
                'verbose_name': 'Habilidade',
                'verbose_name_plural': 'Habilidades',
                'ordering': ['-skill__name'],
                'unique_together': {('evaluation', 'skill')},
            },
        ),
        migrations.AddField(
            model_name='evaluation',
            name='skills',
            field=models.ManyToManyField(related_name='evaluations', through='performance.EvaluationSkill', to='performance.Skill'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='valuator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valuator_evaluations', to='users.Employee', verbose_name='Avaliador'),
        ),
        migrations.AlterUniqueTogether(
            name='evaluation',
            unique_together={('rated', 'year')},
        ),
    ]
