# Generated by Django 2.2 on 2020-08-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20200819_2324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodymassindex',
            options={'verbose_name': 'Indice de Massa Corporal'},
        ),
    ]
