# Generated by Django 2.2 on 2020-08-20 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20200819_2330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodymassindex',
            options={'verbose_name': 'Indice de Massa Corporal', 'verbose_name_plural': 'Indice de Massa Corporal'},
        ),
    ]
