# Generated by Django 2.2 on 2020-08-20 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20200820_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='sap_code',
        ),
    ]
